import type { EcoStop } from "@/types/ecostop";

type DemoStop = EcoStop & { id: string; desk_url_code?: string };

/**
 * Hardcoded demonstration stopdesks for Anderson Logistique E-commerce.
 * Used until the company has its real data wired into Firestore.
 */
export const ANDERSON_DEMO_STOPS: DemoStop[] = [
  {
    id: "anderson-alger-centre",
    desk_url_code: "ANDR-ALG-01",
    name: "Anderson Alger Centre",
    phone: "0550 12 34 56",
    phone2: "0770 12 34 56",
    code_wilaya: 16,
    wilaya: "Alger",
    commune: "Alger Centre",
    adresse: "12 Rue Didouche Mourad, en face de la Grande Poste, Alger Centre",
    map: "https://www.google.com/maps/search/?api=1&query=Rue+Didouche+Mourad+Alger",
    company: "anderson",
  },
  {
    id: "anderson-bab-ezzouar",
    desk_url_code: "ANDR-ALG-02",
    name: "Anderson Bab Ezzouar",
    phone: "0550 23 45 67",
    phone2: null,
    code_wilaya: 16,
    wilaya: "Alger",
    commune: "Bab Ezzouar",
    adresse: "Cité 1100 Logements, Bât B12, Local 3, Bab Ezzouar",
    map: "https://www.google.com/maps/search/?api=1&query=Bab+Ezzouar+Alger",
    company: "anderson",
  },
  {
    id: "anderson-oran-es-senia",
    desk_url_code: "ANDR-ORN-01",
    name: "Anderson Oran Es-Sénia",
    phone: "0540 11 22 33",
    phone2: "0660 11 22 33",
    code_wilaya: 31,
    wilaya: "Oran",
    commune: "Es-Sénia",
    adresse: "Route de l'aéroport, à coté de la station Naftal, Es-Sénia, Oran",
    map: "https://www.google.com/maps/search/?api=1&query=Es-Senia+Oran",
    company: "anderson",
  },
  {
    id: "anderson-oran-bir-el-djir",
    desk_url_code: "ANDR-ORN-02",
    name: "Anderson Oran Bir El Djir",
    phone: "0540 22 33 44",
    phone2: null,
    code_wilaya: 31,
    wilaya: "Oran",
    commune: "Bir El Djir",
    adresse: "Avenue de l'ALN, en face de l'USTO, Bir El Djir",
    map: "https://www.google.com/maps/search/?api=1&query=Bir+El+Djir+Oran",
    company: "anderson",
  },
  {
    id: "anderson-constantine-zouaghi",
    desk_url_code: "ANDR-CST-01",
    name: "Anderson Constantine Zouaghi",
    phone: "0560 33 44 55",
    phone2: null,
    code_wilaya: 25,
    wilaya: "Constantine",
    commune: "Zouaghi Slimane",
    adresse: "Cité Boussouf, Rue des Frères Abbas, Zouaghi Slimane",
    map: "https://www.google.com/maps/search/?api=1&query=Zouaghi+Constantine",
    company: "anderson",
  },
  {
    id: "anderson-annaba-centre",
    desk_url_code: "ANDR-ANB-01",
    name: "Anderson Annaba Centre",
    phone: "0560 44 55 66",
    phone2: "0770 44 55 66",
    code_wilaya: 23,
    wilaya: "Annaba",
    commune: "Annaba",
    adresse: "Cours de la Révolution, à coté du théâtre régional, Annaba",
    map: "https://www.google.com/maps/search/?api=1&query=Cours+Revolution+Annaba",
    company: "anderson",
  },
  {
    id: "anderson-setif-centre",
    desk_url_code: "ANDR-SET-01",
    name: "Anderson Sétif Centre",
    phone: "0550 55 66 77",
    phone2: null,
    code_wilaya: 19,
    wilaya: "Sétif",
    commune: "Sétif",
    adresse: "Avenue du 1er Novembre, en face du parc Aïn El Fouara, Sétif",
    map: "https://www.google.com/maps/search/?api=1&query=Ain+El+Fouara+Setif",
    company: "anderson",
  },
  {
    id: "anderson-blida-centre",
    desk_url_code: "ANDR-BLD-01",
    name: "Anderson Blida Centre",
    phone: "0550 66 77 88",
    phone2: null,
    code_wilaya: 9,
    wilaya: "Blida",
    commune: "Blida",
    adresse: "Boulevard Larbi Tebessi, à coté de la place du 1er Novembre, Blida",
    map: "https://www.google.com/maps/search/?api=1&query=Larbi+Tebessi+Blida",
    company: "anderson",
  },
  {
    id: "anderson-tlemcen-centre",
    desk_url_code: "ANDR-TLM-01",
    name: "Anderson Tlemcen",
    phone: "0540 77 88 99",
    phone2: null,
    code_wilaya: 13,
    wilaya: "Tlemcen",
    commune: "Tlemcen",
    adresse: "Rue de l'Indépendance, en face de la médersa, Tlemcen",
    map: "https://www.google.com/maps/search/?api=1&query=Tlemcen+centre",
    company: "anderson",
  },
  {
    id: "anderson-bejaia-centre",
    desk_url_code: "ANDR-BJA-01",
    name: "Anderson Béjaïa",
    phone: "0560 88 99 00",
    phone2: "0770 88 99 00",
    code_wilaya: 6,
    wilaya: "Béjaïa",
    commune: "Béjaïa",
    adresse: "Boulevard de la Liberté, en face du port, Béjaïa",
    map: "https://www.google.com/maps/search/?api=1&query=Bejaia+port",
    company: "anderson",
  },
  {
    id: "anderson-tizi-ouzou",
    desk_url_code: "ANDR-TZO-01",
    name: "Anderson Tizi Ouzou",
    phone: "0550 99 00 11",
    phone2: null,
    code_wilaya: 15,
    wilaya: "Tizi Ouzou",
    commune: "Tizi Ouzou",
    adresse: "Boulevard Stiti Ali, Nouvelle Ville, Tizi Ouzou",
    map: "https://www.google.com/maps/search/?api=1&query=Nouvelle+Ville+Tizi+Ouzou",
    company: "anderson",
  },
  {
    id: "anderson-batna-centre",
    desk_url_code: "ANDR-BTN-01",
    name: "Anderson Batna",
    phone: "0560 10 20 30",
    phone2: null,
    code_wilaya: 5,
    wilaya: "Batna",
    commune: "Batna",
    adresse: "Avenue de la République, près du marché central, Batna",
    map: "https://www.google.com/maps/search/?api=1&query=Batna+centre",
    company: "anderson",
  },
];

/**
 * Hardcoded demonstration stopdesks for imir Logistics.
 */
export const IMIR_DEMO_STOPS: DemoStop[] = [
  {
    id: "imir-alger-centre",
    desk_url_code: "IMIR-ALG-01",
    name: "imir Alger Centre",
    phone: "0550 14 25 36",
    phone2: "0770 14 25 36",
    code_wilaya: 16,
    wilaya: "Alger",
    commune: "Alger Centre",
    adresse: "23 Boulevard Mohamed V, près de la place Audin, Alger Centre",
    map: "https://www.google.com/maps/search/?api=1&query=Boulevard+Mohamed+V+Alger",
    company: "imir",
  },
  {
    id: "imir-hydra",
    desk_url_code: "IMIR-ALG-02",
    name: "imir Hydra",
    phone: "0550 25 36 47",
    phone2: null,
    code_wilaya: 16,
    wilaya: "Alger",
    commune: "Hydra",
    adresse: "Rue des Frères Bouadou, à coté du parc Hydra, Hydra",
    map: "https://www.google.com/maps/search/?api=1&query=Hydra+Alger",
    company: "imir",
  },
  {
    id: "imir-oran-centre",
    desk_url_code: "IMIR-ORN-01",
    name: "imir Oran Centre",
    phone: "0540 36 47 58",
    phone2: "0660 36 47 58",
    code_wilaya: 31,
    wilaya: "Oran",
    commune: "Oran",
    adresse: "Boulevard de la Soummam, en face de la place du 1er Novembre, Oran",
    map: "https://www.google.com/maps/search/?api=1&query=Boulevard+Soummam+Oran",
    company: "imir",
  },
  {
    id: "imir-constantine",
    desk_url_code: "IMIR-CST-01",
    name: "imir Constantine",
    phone: "0560 47 58 69",
    phone2: null,
    code_wilaya: 25,
    wilaya: "Constantine",
    commune: "Constantine",
    adresse: "Rue Larbi Ben M'hidi, près du pont Sidi Rached, Constantine",
    map: "https://www.google.com/maps/search/?api=1&query=Sidi+Rached+Constantine",
    company: "imir",
  },
  {
    id: "imir-setif",
    desk_url_code: "IMIR-SET-01",
    name: "imir Sétif",
    phone: "0550 58 69 70",
    phone2: null,
    code_wilaya: 19,
    wilaya: "Sétif",
    commune: "Sétif",
    adresse: "Avenue du 8 Mai 1945, à coté de la gare routière, Sétif",
    map: "https://www.google.com/maps/search/?api=1&query=8+Mai+1945+Setif",
    company: "imir",
  },
  {
    id: "imir-annaba",
    desk_url_code: "IMIR-ANB-01",
    name: "imir Annaba",
    phone: "0560 69 70 81",
    phone2: "0770 69 70 81",
    code_wilaya: 23,
    wilaya: "Annaba",
    commune: "Annaba",
    adresse: "Boulevard du 1er Novembre, près du port, Annaba",
    map: "https://www.google.com/maps/search/?api=1&query=1er+Novembre+Annaba",
    company: "imir",
  },
  {
    id: "imir-blida",
    desk_url_code: "IMIR-BLD-01",
    name: "imir Blida",
    phone: "0550 70 81 92",
    phone2: null,
    code_wilaya: 9,
    wilaya: "Blida",
    commune: "Blida",
    adresse: "Rue Tirsatine, en face du marché couvert, Blida",
    map: "https://www.google.com/maps/search/?api=1&query=Blida+centre",
    company: "imir",
  },
  {
    id: "imir-tizi-ouzou",
    desk_url_code: "IMIR-TZO-01",
    name: "imir Tizi Ouzou",
    phone: "0550 81 92 03",
    phone2: null,
    code_wilaya: 15,
    wilaya: "Tizi Ouzou",
    commune: "Tizi Ouzou",
    adresse: "Boulevard Krim Belkacem, Nouvelle Ville, Tizi Ouzou",
    map: "https://www.google.com/maps/search/?api=1&query=Krim+Belkacem+Tizi+Ouzou",
    company: "imir",
  },
];

/**
 * Hardcoded demonstration stopdesks for RedEx.
 */
export const REDEX_DEMO_STOPS: DemoStop[] = [
  {
    id: "redex-alger-centre",
    desk_url_code: "REDEX-ALG-01",
    name: "RedEx Alger Centre",
    phone: "0551 10 20 30",
    phone2: "0771 10 20 30",
    code_wilaya: 16,
    wilaya: "Alger",
    commune: "Alger Centre",
    adresse: "45 Rue Didouche Mourad, près de la Faculté, Alger Centre",
    map: "https://www.google.com/maps/search/?api=1&query=Didouche+Mourad+Alger",
    company: "redex",
  },
  {
    id: "redex-bab-ezzouar",
    desk_url_code: "REDEX-ALG-02",
    name: "RedEx Bab Ezzouar",
    phone: "0551 20 30 40",
    phone2: null,
    code_wilaya: 16,
    wilaya: "Alger",
    commune: "Bab Ezzouar",
    adresse: "Centre commercial Bab Ezzouar, niveau 1, Bab Ezzouar",
    map: "https://www.google.com/maps/search/?api=1&query=Bab+Ezzouar+Alger",
    company: "redex",
  },
  {
    id: "redex-oran",
    desk_url_code: "REDEX-ORN-01",
    name: "RedEx Oran",
    phone: "0541 30 40 50",
    phone2: "0661 30 40 50",
    code_wilaya: 31,
    wilaya: "Oran",
    commune: "Oran",
    adresse: "Rue Larbi Ben M'hidi, en face de la mairie, Oran",
    map: "https://www.google.com/maps/search/?api=1&query=Larbi+Ben+Mhidi+Oran",
    company: "redex",
  },
  {
    id: "redex-constantine",
    desk_url_code: "REDEX-CST-01",
    name: "RedEx Constantine",
    phone: "0561 40 50 60",
    phone2: null,
    code_wilaya: 25,
    wilaya: "Constantine",
    commune: "Constantine",
    adresse: "Boulevard Zaabane, près de la place des Martyrs, Constantine",
    map: "https://www.google.com/maps/search/?api=1&query=Zaabane+Constantine",
    company: "redex",
  },
  {
    id: "redex-setif",
    desk_url_code: "REDEX-SET-01",
    name: "RedEx Sétif",
    phone: "0551 50 60 70",
    phone2: null,
    code_wilaya: 19,
    wilaya: "Sétif",
    commune: "Sétif",
    adresse: "Avenue du 1er Novembre, à coté du parc d'attractions, Sétif",
    map: "https://www.google.com/maps/search/?api=1&query=1er+Novembre+Setif",
    company: "redex",
  },
  {
    id: "redex-annaba",
    desk_url_code: "REDEX-ANB-01",
    name: "RedEx Annaba",
    phone: "0561 60 70 80",
    phone2: "0771 60 70 80",
    code_wilaya: 23,
    wilaya: "Annaba",
    commune: "Annaba",
    adresse: "Cours de la Révolution, centre-ville, Annaba",
    map: "https://www.google.com/maps/search/?api=1&query=Cours+Revolution+Annaba",
    company: "redex",
  },
  {
    id: "redex-blida",
    desk_url_code: "REDEX-BLD-01",
    name: "RedEx Blida",
    phone: "0551 70 80 90",
    phone2: null,
    code_wilaya: 9,
    wilaya: "Blida",
    commune: "Blida",
    adresse: "Boulevard Ben Boulaid, près de la gare, Blida",
    map: "https://www.google.com/maps/search/?api=1&query=Ben+Boulaid+Blida",
    company: "redex",
  },
  {
    id: "redex-bejaia",
    desk_url_code: "REDEX-BJA-01",
    name: "RedEx Béjaïa",
    phone: "0561 80 90 10",
    phone2: null,
    code_wilaya: 6,
    wilaya: "Béjaïa",
    commune: "Béjaïa",
    adresse: "Rue de la Liberté, près du port, Béjaïa",
    map: "https://www.google.com/maps/search/?api=1&query=Bejaia+centre",
    company: "redex",
  },
];

export const DEMO_STOPS_BY_COMPANY: Record<string, DemoStop[]> = {
  anderson: ANDERSON_DEMO_STOPS,
  imir: IMIR_DEMO_STOPS,
  redex: REDEX_DEMO_STOPS,
};

/** Find a single demo stopdesk by its URL code (case-insensitive). */
export const findDemoStop = (urlcode: string): DemoStop | undefined => {
  const code = decodeURIComponent(urlcode || "").trim().toLowerCase();
  if (!code) return undefined;
  for (const stops of Object.values(DEMO_STOPS_BY_COMPANY)) {
    const match = stops.find(
      (s) =>
        s.desk_url_code?.toLowerCase() === code || s.id.toLowerCase() === code
    );
    if (match) return match;
  }
  return undefined;
};
